stop_words = [
    "draw",
    "ac",
    "athletic club",
    "associazione di calcio",
    "afc",
    "association football club",
    "bsc",
    "ballspielclub",
    "bk",
    "boldspill klub",
    "ca",
    "club atlético",
    "cd",
    "club deportivo",
    "cf",
    "club de fútbol",
    "cr",
    "clube de regatas",
    "cs",
    "club du sport",
    "club social",
    "csd",
    "club social y deportivo",
    "fc",
    "football club",
    "erster fußball club",
    "ia",
    "institición atlética",
    "rc",
    "racing club",
    "real club",
    "sa",
    "soccer association",
    "sc",
    "sporting club",
    "soccer club",
    "erster sport club",
    "sv",
    "sportsverein",
    "sportverein",
    "spielvereinigung",
    "fk",
    "fußballklub",
    "fv",
    "fußballverein",
    "sg",
    "spielgemeinschaft",
    "sportgruppe",
    "spvgg",
    "spielvereinigung",
    "svg",
    "spielvereinigung",
    "tsv",
    "turn und sportverein",
    "tus",
    "turn und sportverein",
    "bv",
    "ballsportverein",
    "bsv",
    "ballsportverein",
    "vfb",
    "verein für bewegungsspiele",
    "vfl",
    "verein für leibesübungen",
    "tv",
    "turnverein",
    "ssv",
    "schwimm und sportverein",
    "usc",
    "universitätssportverein",
    "e.v.",
    "eingetragener verein",
    "club",
    "athletic",
    "athletic club",
    "deportivo",
    "deportivo club",
    "racing club",
    "racing",
    "universitario",
    "universitaria",
    "sporting",
    "social",
    "social club",
    "social y deportivo",
    "verein",
    "vereins",
    "association",
    "union",
    "mens",
    "men",
    "womens",
    "women",
]
