stop_words = [
    "(",
    ")",
    ";",
    "/",
    "-",
    ".",
    ",",
    "reserves",
    "bb",
    "belediye",
    "belediyespor",
    "pfc",
    "al",
    "sportsklubben",
    "sk",
    "vfv",
    "united",
    "town",
    "city",
    "olympic",
    "county",
    "real",
    "olympique",
    "ac",
    "us",
    "athletic",
    "associazione",
    "di",
    "calcio",
    "afc",
    "association",
    "bsc",
    "ballspielclub",
    "bk",
    "boldspill",
    "klub",
    "ca",
    "atlético",
    "cd",
    "cf",
    "de",
    "fútbol",
    "cr",
    "clube",
    "regatas",
    "cs",
    "club",
    "du",
    "sport",
    "social",
    "csd",
    "y",
    "deportivo",
    "fc",
    "football",
    "erster",
    "fußball",
    "ia",
    "institición",
    "atlética",
    "rc",
    "racing",
    "sa",
    "soccer",
    "sc",
    "sporting",
    "sv",
    "sportsverein",
    "sportverein",
    "spielvereinigung",
    "fk",
    "fußballklub",
    "fv",
    "fußballverein",
    "sg",
    "spielgemeinschaft",
    "sportgruppe",
    "spvgg",
    "svg",
    "tsv",
    "und",
    "tus",
    "turn",
    "bv",
    "bsv",
    "ballsportverein",
    "vfb",
    "für",
    "bewegungsspiele",
    "vfl",
    "verein",
    "leibesübungen",
    "tv",
    "turnverein",
    "ssv",
    "schwimm",
    "usc",
    "universitätssportverein",
    "e.v.",
    "eingetragener",
    "atletico",
    "dynamo",
    "inter",
    "international",
    "universitario",
    "universitaria",
    "vereins",
    "union",
    "mens",
    "men",
    "womens",
    "women",
    "as",
    "sportiva",
    "junior",
    "wanderers",
    "rovers",
    "rangers",
    "u12",
    "u14",
    "u15",
    "u16",
    "u17",
    "u19",
    "u20",
    "u21",
    "u23",
    "o30",
    "o35",
    "usd",
    "amateur",
    "vis",
    "asd",
    "wfc",
    "saint",
    "st"
]

stream_config = {
    "btts": {
        "live": "BTTS_live_stream",
        "upcoming": "BTTS_upcoming_stream",
        "least_count": 2,
        "lst": 3,
        "xtr": 3,
    },
    "double_chance": {
        "live": "DOUBLE_CHANCE_live_stream",
        "upcoming": "DOUBLE_CHANCE_upcoming_stream",
        "least_count": 3,
        "lst": 3,
        "xtr": 3,
    },
    "three_way": {
        "live": "THREE_WAY_live_stream",
        "upcoming": "THREE_WAY_upcoming_stream",
        "least_count": 3,
        "lst": 3,
        "xtr": 3,
    },
}
