stop_words = [
    "(",
    ")",
    ";",
    "/",
    "-",
    ".",
    ",",
    "reserves",
    "bb",
    "belediye",
    "belediyespor",
    "pfc",
    "al",
    "sportsklubben",
    "sk",
    "vfv",
    "united",
    "utd",
    "town",
    "city",
    "olympic",
    "county",
    "real",
    "olympique",
    "ac",
    "us",
    "athletic",
    "associazione",
    "di",
    "calcio",
    "afc",
    "association",
    "bsc",
    "ballspielclub",
    "bk",
    "boldspill",
    "klub",
    "ca",
    "atlético",
    "cd",
    "cf",
    "de",
    "fútbol",
    "cr",
    "clube",
    "regatas",
    "cs",
    "club",
    "du",
    "sport",
    "social",
    "csd",
    "y",
    "deportivo",
    "fc",
    "football",
    "erster",
    "fußball",
    "ia",
    "institición",
    "atlética",
    "rc",
    "racing",
    "sa",
    "soccer",
    "sc",
    "sporting",
    "sv",
    "sportsverein",
    "sportverein",
    "spielvereinigung",
    "fk",
    "fußballklub",
    "fv",
    "fußballverein",
    "sg",
    "spielgemeinschaft",
    "sportgruppe",
    "spvgg",
    "svg",
    "tsv",
    "und",
    "tus",
    "turn",
    "bv",
    "bsv",
    "ballsportverein",
    "vfb",
    "für",
    "bewegungsspiele",
    "vfl",
    "verein",
    "leibesübungen",
    "tv",
    "turnverein",
    "ssv",
    "schwimm",
    "usc",
    "universitätssportverein",
    "e.v.",
    "eingetragener",
    "atletico",
    "dynamo",
    "inter",
    "international",
    "universitario",
    "universitaria",
    "vereins",
    "union",
    "mens",
    "men",
    "womens",
    "women",
    "wom",
    "lfc",
    "as",
    "eintracht",
    "pae",
    "aek",
    "ae",
    "sportiva",
    "junior",
    "wanderers",
    "rovers",
    "rangers",
    "u12",
    "u14",
    "u15",
    "u16",
    "u17",
    "u19",
    "u20",
    "u21",
    "u23",
    "o30",
    "o35",
    "usd",
    "amateur",
    "vis",
    "asd",
    "wfc",
    "saint",
    "st",
]

match_words = [
    "eintracht",
    "pae",
    "aek",
    "ae",
    "reserves",
    "bb",
    "belediye",
    "belediyespor",
    "pfc",
    "al",
    "sportsklubben",
    "sk",
    "vfv",
    "united",
    "utd",
    "town",
    "city",
    "olympic",
    "county",
    "real",
    "olympique",
    "ac",
    "us",
    "athletic",
    "associazione",
    "di",
    "calcio",
    "afc",
    "association",
    "bsc",
    "ballspielclub",
    "bk",
    "boldspill",
    "klub",
    "ca",
    "atlético",
    "cd",
    "cf",
    "de",
    "fútbol",
    "cr",
    "clube",
    "regatas",
    "cs",
    "club",
    "du",
    "sport",
    "social",
    "csd",
    "y",
    "deportivo",
    "fc",
    "football",
    "erster",
    "fußball",
    "ia",
    "institición",
    "atlética",
    "rc",
    "sa",
    "soccer",
    "sc",
    "sporting",
    "sv",
    "sportsverein",
    "sportverein",
    "spielvereinigung",
    "fk",
    "fußballklub",
    "fv",
    "fußballverein",
    "sg",
    "spielgemeinschaft",
    "sportgruppe",
    "spvgg",
    "svg",
    "tsv",
    "und",
    "tus",
    "turn",
    "bv",
    "bsv",
    "ballsportverein",
    "vfb",
    "für",
    "bewegungsspiele",
    "vfl",
    "verein",
    "leibesübungen",
    "tv",
    "turnverein",
    "ssv",
    "schwimm",
    "usc",
    "universitätssportverein",
    "e.v.",
    "eingetragener",
    "atletico",
    "dynamo",
    "inter",
    "international",
    "universitario",
    "universitaria",
    "vereins",
    "union",
    "mens",
    "men",
    "womens",
    "women",
    "wom",
    "lfc",
    "as",
    "sportiva",
    "junior",
    "wanderers",
    "rovers",
    "rangers",
    "u12",
    "u14",
    "u15",
    "u16",
    "u17",
    "u19",
    "u20",
    "u21",
    "u23",
    "o30",
    "o35",
    "usd",
    "amateur",
    "vis",
    "asd",
    "wfc",
    "saint",
    "st",
    "stade",
    "entente",
    "racing",
    "psv",
    "ajax",
    "den",
    "het",
    "van",
    "quick",
    "boys",
    "jong",
    "voetbal",
    "vereniging",
    "ks",
    "klub",
    "sportowy",
    "wisla",
    "legia",
    "pogon",
    "gornik",
    "zaglebie",
    "cska",
    "zenit",
    "spartak",
    "lokomotiv",
    "torpedo",
    "krylya",
    "rubin",
    "west",
    "east",
    "north",
    "south",
    "western",
    "eastern",
    "northern",
    "southern",
    "central",
    "roja",
    "red",
    "blues",
    "azul",
    "bianco",
    "blanc",
    "blanco",
    "verde",
    "viola",
    "professional",
    "pro",
    "academy",
    "development",
    "youth",
    "academie",
    "academia",
    "szkola",
    "champions",
    "premier",
    "primera",
    "bundesliga",
    "liga",
    "ligue",
    "series",
    "division",
    "albion",
    "hotspur",
    "thistle",
    "borough",
    "foundation",
    "fundacion",
    "institute",
    "instituto",
    "asc",
    "rsc",
    "psg",
    "bvb",
    "ogc",
    "rcl",
    "fcb",
    "acf",
    "ssc",
    "vvv",
]

IDENTIFIER_GROUPS = {
    "women": {"women", "womens", "wom", "wfc"},
    "men": {"men", "mens"},
    "united": {"united", "utd"},
    "football": {
        "fc",
        "football",
        "fußball",
        "calcio",
        "soccer",
        "voetbal",
        "futbol",
        "fútbol",
        # Common football abbreviations
        "lfc",
        "afc",
        "usc",
        "pfc",
        "fcb",
        "psv",
        "bvb",
    },
    "association":"ac",
    "saint": {"saint", "st"},
    "greek": {"pae", "ae", "aek"},
    "club": {"club", "clube"},
    "sport": {"sport", "sports", "sporting", "sportiva"},
    "athletic": {"athletic", "atlético", "atletico", "ca"},
    "association": {"associazione", "association"},
    "german_club": {
        "verein",
        "vereins",
        "bsc",
        "ballspielclub",
        "bv",
        "bsv",
        "ballsportverein",
        "sv",
        "sportsverein",
        "sportverein",
        "fk",
        "fußballklub",
        "fv",
        "fußballverein",
        "vfv",
        "sg",
        "spielgemeinschaft",
        "sportgruppe",
        "spvgg",
        "spielvereinigung",
    },
    "turkish": {"belediye", "belediyespor"},
    "scandinavian": {"sk", "sportsklubben", "bk", "boldspill", "klub"},
    "university": {"universitario", "universitaria"},
    "international": {"inter", "international", "ifc"},
    "age_groups": {
        # Under age groups
        "u12",
        "u13",
        "u14",
        "u15",
        "u16",
        "u17",
        "u18",
        "u19",
        "u20",
        "u21",
        "u22",
        "u23",
        "u25",
        "under12",
        "under13",
        "under14",
        "under15",
        "under16",
        "under17",
        "under18",
        "under19",
        "under20",
        "under21",
        "under23",
        # Over age groups
        "o30",
        "o35",
        "o40",
        "o45",
        "o50",
        "over30",
        "over35",
        "over40",
    },
    "team_identity": {
        # Basic identifiers
        "united",
        "utd",
        "city",
        "town",
        "county",
        "borough",
        "albion",
        "hotspur",
        "thistle",
        # Wanderer types
        "wanderers",
        "rovers",
        "rangers",
        # Military/strength related
        "arsenal",
        "warriors",
        "knights",
        "legion",
        "victoria",
        "victory",
        "gloria",
        # Vehicle/transport related
        "lokomotiv",
        "locomotive",
        "torpedo",
        # Power/energy related
        "dinamo",
        "dynamo",
    },
}

IDENTIFIERS_GROUPED = {
    # Gender-specific identifiers
    "gender": {"women", "womens", "wom", "wfc", "men", "mens"},
    # Core football/soccer terms
    "football": {
        "fc",
        "football",
        "fußball",
        "calcio",
        "soccer",
        "voetbal",
        "futbol",
        "fútbol",
        # Common football abbreviations
        "lfc",
        "wfc",
        "afc",
        "usc",
        "pfc",
        "fcb",
        "psv",
        "bvb",
    },
    # Team types and identifiers
    "team_identity": {
        # Basic identifiers
        "united",
        "utd",
        "city",
        "town",
        "county",
        "borough",
        "albion",
        "hotspur",
        "thistle",
        # Wanderer types
        "wanderers",
        "rovers",
        "rangers",
        # Military/strength related
        "arsenal",
        "warriors",
        "knights",
        "legion",
        "victoria",
        "victory",
        "gloria",
        # Vehicle/transport related
        "lokomotiv",
        "locomotive",
        "torpedo",
        # Power/energy related
        "dinamo",
        "dynamo",
    },
    # Organization and association terms
    "organization": {
        # Basic terms
        "club",
        "clube",
        "association",
        "associazione",
        "associacao",
        "foundation",
        "fundacion",
        "institute",
        "instituto",
        # Educational
        "academy",
        "academia",
        "school",
        "college",
        # Status related
        "professional",
        "amateur",
        "pro",
        "reserves",
        "development",
        "youth",
        "junior",
        "seniors",
        # German specific
        "verein",
        "vereins",
        "sportverein",
        "universitätssportverein",
        "ballsportverein",
        "fußballverein",
        "turnverein",
        "spielvereinigung",
        "eingetragener",
        "e.v.",
    },
    # Sport and athletic terms
    "sports_terms": {
        "sport",
        "sports",
        "sporting",
        "sportiva",
        "sportive",
        "athletic",
        "atlético",
        "atletico",
        "athletics",
        "olympique",
        "olympic",
        "social",
        "racing",
    },
    # Common abbreviations and short forms
    "abbreviations": {
        # General
        "ac",
        "as",
        "sc",
        "ca",
        "cd",
        "cf",
        "cs",
        "csd",
        "rc",
        # Extended
        "asc",
        "rsc",
        "psg",
        "tsg",
        "ogc",
        "rcl",
        "acf",
        "ssc",
        "vvv",
        # German
        "bsc",
        "bv",
        "bsv",
        "sv",
        "fk",
        "fv",
        "vfv",
        "sg",
        "spvgg",
        "tsv",
        "tus",
        "vfb",
        "vfl",
        "tv",
        "ssv",
        # Other regions
        "ae",
        "aek",
        "pae",
        "ks",
        "sk",
        "bk",
    },
    # Location and geographic terms
    "geographic": {
        # Directions
        "west",
        "east",
        "north",
        "south",
        "western",
        "eastern",
        "northern",
        "southern",
        # Scope
        "central",
        "regional",
        "nacional",
        "national",
        "inter",
        "international",
    },
    # Competition and level indicators
    "competition": {
        "champions",
        "premier",
        "primera",
        "bundesliga",
        "liga",
        "ligue",
        "series",
        "division",
    },
    # Age group identifiers
    "age_groups": {
        # Under age groups
        "u12",
        "u13",
        "u14",
        "u15",
        "u16",
        "u17",
        "u18",
        "u19",
        "u20",
        "u21",
        "u22",
        "u23",
        "u25",
        "under12",
        "under13",
        "under14",
        "under15",
        "under16",
        "under17",
        "under18",
        "under19",
        "under20",
        "under21",
        "under23",
        # Over age groups
        "o30",
        "o35",
        "o40",
        "o45",
        "o50",
        "over30",
        "over35",
        "over40",
    },
    # Colors
    "colors": {
        # Basic colors
        "red",
        "green",
        "yellow",
        "blue",
        "blues",
        # International variants
        "roja",
        "azul",
        "amarillo",
        "verde",
        "bianco",
        "blanc",
        "blanco",
        "viola",
        "violets",
    },
    # Regional/Language specific terms
    "regional": {
        # German specific organizational terms
        "für",
        "bewegungsspiele",
        "leibesübungen",
        "schwimm",
        "turn",
        "eintracht",
        "spielgemeinschaft",
        "sportgruppe",
        # Turkish
        "belediye",
        "belediyespor",
        # Scandinavian
        "sportsklubben",
        "boldspill",
        "klub",
        # University related
        "universitäts",
        "universitario",
        "universitaria",
        # French
        "stade",
        "entente",
        # Dutch
        "ajax",
        "den",
        "het",
        "van",
        "quick",
        "boys",
        "jong",
        # Polish
        "sportowy",
        "wisla",
        "legia",
        "pogon",
        "gornik",
        "zaglebie",
        # Russian
        "cska",
        "zenit",
        "spartak",
        "krylya",
        "rubin",
        # Latin/Spanish/Portuguese
        "deportivo",
        "regatas",
        "di",
        # Educational
        "szkola",
        "escuela",
        "academie",
    },
    # Religious/Honorary
    "religious": {"saint", "st"},
}

stream_config = {
    "btts": {
        "live": "BTTS_live_stream",
        "upcoming": "BTTS_upcoming_stream",
        "least_count": 2,
        "lst": 3,
        "xtr": 3,
    },
    "double_chance": {
        "live": "DOUBLE_CHANCE_live_stream",
        "upcoming": "DOUBLE_CHANCE_upcoming_stream",
        "least_count": 3,
        "lst": 3,
        "xtr": 3,
    },
    "three_way": {
        "live": "THREE_WAY_live_stream",
        "upcoming": "THREE_WAY_upcoming_stream",
        "least_count": 3,
        "lst": 3,
        "xtr": 3,
    },
}
